services:
  - type: web
    name: quantumpay-api
    env: python
    region: singapore
    buildCommand: "pip install -r backend/requirements.txt && pip install qiskit qiskit-ibm-runtime"
    startCommand: "python backend/main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: IBM_QUANTUM_TOKEN
        sync: false
